IM_SIZE = 48

# Neural Network config
CONV_FILTERS = [32, 48]
CONV_KERNEL_SIZES = [6, 5]
CONV_STRIDES = [2, 2]
POST_CONV_DENSE_SIZE = 512
DUELING_DEPTH = 3
DUELING_LAYER_SIZE = 512

KAPPA = -1e-2
DENSE_INIT = 'glorot_uniform'

BLACK_AND_WHITE = False
